### ISSUE TITLE
AttributeError: '_ColumnEntity' object has no attribute 'mapper'

### ISSUE THREAD

**Issue by NeilBetham** [Murodese/pynab#300]
I was doing a fresh install recently and ran into this exception in the post processor:

```
Traceback (most recent call last):
  File "/pynab/postprocess.py", line 235, in <module>
    main()
  File "/pynab/postprocess.py", line 198, in main
    deleted_nzbs = db.query(NZB.id).filter(NZB.release == None).delete(synchronize_session='fetch')
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 3153, in delete
    delete_op.exec_()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 1158, in exec_
    self._do_post_synchronize()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/persistence.py", line 1427, in _do_post_synchronize
    target_mapper = self.query._mapper_zero()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py", line 294, in _mapper_zero
    return self._entities[0].mapper
AttributeError: '_ColumnEntity' object has no attribute 'mapper'
```

When the query is performed on just the `id` column it seems to trip up the delete call. I tested by updating to query to be on the whole model and it worked without issue after that. Is there a reason the query is just on the `id` column?

**Comment by ukharley** [comment]
This happened to me when I updated my SQLAlchemy from 1.0.12 to 1.1.3. Had to revert back. Code either needs to be fixed or SQLAlchamey locked to below 1.1.3

**Comment by NeilBetham** [comment]
I updated it to just query against the whole model instead of just the `id` column and that seems to have fixed the issue. I've been running off of that without issue for a bit now.

**Comment by brookesy2** [comment]
Fixed in https://github.com/Murodese/pynab/pull/301
