### ISSUE TITLE
Error: suspected dead nntp connection, restarting for some groups

### ISSUE THREAD

**Issue by brookesy2** [Murodese/pynab#109]
Seems there is an odd post in the below causing issues (Could just be me?):

alt.binaries.hdtv (around 4908864337)
alt.binaries.teevee (around 714625928)

Essentially if either of those groups are enabled I get (just hdtv message below, teevee is the same:

2014-12-26 21:25:24,101 - ERROR -  server: [alt.binaries.hdtv]: nntp error
2014-12-26 21:25:24,101 - ERROR -  server: suspected dead nntp connection, restarting

Created a clean install of pynab and only went back 1 day and it will index hdtv/teevee correctly. If I set the clean install to the same last as my main install, it throws the same error

Anyone else getting this? Any tips for debugging?

**Comment by Murodese** [comment]
Yeah, 22350 just prevents an exception when you quit a connection (because doing so sends a QUIT command to the socket, and if the socket is already dead it'll throw an exception). Not much help with that. I've merged compression support into the latest nntplib anyway, since there's a few bugfixes and exception cleanups.

Unfortunately I can't really test any code, since I'm really far away from my db server. There's a few things that immediately stand out in that nntplib dump though:

in the first one, ':bytes' should be a long value indicating the length of the message - so '8n53aat1pb3co88i634o3g6lvdfheeuf7o@4ax.com' obviously isn't a valid value. Double-check whatever logic you're using to print the keys/vals just to make sure they line up properly. If that's fine, that's one of the issues. Similarly in the second one, bytes is null.

I'll implement far more stringent checking of datatypes - I assumed that it was the server managing the :bytes metadata, but maybe not.

**Comment by Murodese** [comment]
Try that. Should be much less forgiving of errors in messages, any dead ones will get spammed out to debug as 'server: bad message: {message overview}'.

**Comment by brookesy2** [comment]
I will check later today. Perhaps my debugs in nntplib are getting mixed up somehow. Though if i write a small script to just pull the article with message-id 'BYudncCBH9rU0z_JnZ2dnUVZ5g2dnZ2d@giganews.com', I get no such article.

**Comment by ukharley** [comment]
More info, half hour or so after server.py update (never had a problem with a.b.movies before):

2015-01-01 12:06:23 - ERROR - server: [alt.binaries.movies]: nntp error line too long
2015-01-01 12:06:23 - ERROR - server: first [1547918335]: last 1547920560
2015-01-01 12:06:25 - INFO - server: [alt.binaries.movies]: retrieved 1547918335 - 1547920560 in 0.45s [0 recv, 0 pts, 0 ign, 0 blk]
2015-01-01 12:07:28 - ERROR - server: [alt.binaries.movies]: nntp error line too long
2015-01-01 12:07:28 - ERROR - server: first [1547918335]: last 1547921226
2015-01-01 12:07:28 - ERROR - server: suspected dead nntp connection, restarting
2015-01-01 12:07:30 - ERROR - server: [alt.binaries.movies]: nntp error line too long
2015-01-01 12:07:30 - ERROR - server: first [1547918335]: last 1547921226
2015-01-01 12:07:30 - ERROR - server: suspected dead nntp connection, restarting
2015-01-01 12:07:31 - ERROR - server: [alt.binaries.movies]: nntp error line too long
2015-01-01 12:07:31 - ERROR - server: first [1547918335]: last 1547921226

till eventually

2015-01-01 12:08:01 - ERROR - server: suspected dead nntp connection, restarting
2015-01-01 12:08:07 - ERROR - server: could not connect to news server: 502 Your per-user connection limit reached
2015-01-01 12:08:07 - ERROR - server: [alt.binaries.movies]: nntp error 'NoneType' object has no attribute 'group'

**Comment by Murodese** [comment]
Ugh, servers aren't following set standards. Revert that commit for a temp fix, I'll take a look tomorrow.

**Comment by ukharley** [comment]
I upped _MAXLINE = 8192 in nntplib and so for it's holding.

**Comment by brookesy2** [comment]
Oddly I was never getting max line issues. Is there a way to better close out the connection so after a while we don't end up with 502's? I guess that is a part fix for the dead nntp error. Doesn't really solve the issue, but helps a bit I guess.

**Comment by Murodese** [comment]
Probably depends on the client people are using to upload binaries, so maybe the group you're indexing don't have the same issue. We're also only getting headers, so it comes down to the news server as well. NNTP is not wonderfully standardised, annoyingly.

With the new version of nntplib, we're able to quit properly without it breaking madly, so I'll add that back in.

**Comment by brookesy2** [comment]
Oddly I actually tried that fix a while ago to see if it would exit correctly, but it causes a larger error to bubble up when encountering the dodgy articles (I thought it was just me doing something wrong!).

This is on my pynab install setup to hit the dodgy articles every time.

2015-01-02 10:40:24,012 - CRITICAL -  Traceback (most recent call last):
  File "/media/storage/git/pynab/pynab/server.py", line 114, in scan
    status, overviews = self.connection.over((first, last))
  File "/media/storage/git/pynab/lib/nntplib.py", line 964, in over
    return resp, _parse_overview(lines, fmt)
  File "/media/storage/git/pynab/lib/nntplib.py", line 235, in _parse_overview
    raise NNTPDataError("OVER/XOVER response doesn't include "
lib.nntplib.NNTPDataError: OVER/XOVER response doesn't include names of additional headers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/storage/git/pynab/pynab/server.py", line 101, in scan
    self.connection.group(group_name)
  File "/media/storage/git/pynab/lib/nntplib.py", line 771, in group
    resp = self._shortcmd('GROUP ' + name)
  File "/media/storage/git/pynab/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP_SSL' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/storage/git/pynab/lib/nntplib.py", line 1066, in quit
    resp = self._shortcmd('QUIT')
  File "/media/storage/git/pynab/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP_SSL' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/storage/git/pynab/pynab/groups.py", line 78, in scan
    status, parts, messages, missed = server.scan(group_name, first=begin, last=end)
  File "/media/storage/git/pynab/pynab/server.py", line 121, in scan
    return self.scan(group_name, first, last, message_ranges)
  File "/media/storage/git/pynab/pynab/server.py", line 119, in scan
    self.connection.quit()
  File "/media/storage/git/pynab/lib/nntplib.py", line 1068, in quit
    self._close()
  File "/media/storage/git/pynab/lib/nntplib.py", line 1220, in _close
    _NNTPBase._close(self)
  File "/media/storage/git/pynab/lib/nntplib.py", line 1059, in _close
    self.file.close()
AttributeError: 'NNTP_SSL' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/storage/git/pynab/lib/nntplib.py", line 1066, in quit
    resp = self._shortcmd('QUIT')
  File "/media/storage/git/pynab/lib/nntplib.py", line 611, in _shortcmd
    self._putcmd(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 438, in _putcmd
    self._putline(line)
  File "/media/storage/git/pynab/lib/nntplib.py", line 430, in _putline
    self.file.write(line)
AttributeError: 'NNTP_SSL' object has no attribute 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "start.py", line 25, in update
    return pynab.groups.scan(group_name, limit=config.scan.get('group_scan_limit', 2000000))
  File "/media/storage/git/pynab/pynab/groups.py", line 116, in scan
    return True
  File "/media/storage/git/pynab/pynab/server.py", line 31, in __exit__
    self.connection.quit()
  File "/media/storage/git/pynab/lib/nntplib.py", line 1068, in quit
    self._close()
  File "/media/storage/git/pynab/lib/nntplib.py", line 1220, in _close
    _NNTPBase._close(self)
  File "/media/storage/git/pynab/lib/nntplib.py", line 1059, in _close
    self.file.close()
AttributeError: 'NNTP_SSL' object has no attribute 'file'

**Comment by Murodese** [comment]
Sorry, I'll have to look at this in the morning.

**Comment by brookesy2** [comment]
No stress :) Thanks for your continued help!

**Comment by Murodese** [comment]
Ok, so using my provider (supernews) and a.b.teevee range 714685305, 715587937, I don't get an error. As said, this could either be because my provider's not broken, or it could be because the messages aren't numbered the same on providers (which they're not). Hence, you're going to need to provide me some data :)

Chuck this into nntplib.py:

lib/nntplib.py:215: (just before n_defaults = ...)
    print(fmt)
lib/nntplib.py:235: (just before raise NNTPDataError...) 
    print('{} {}'.format(i, token))
    print(line)

Send me any output that you get. Also tell me which provider you're with :)

**Comment by brookesy2** [comment]
Fortunately I was debugging in the exact same area :)

['subject', 'from', 'date', 'message-id', 'references', ':bytes', ':lines', 'xref']

7 3702

4908878442      [REPOST]-[a.b.teevee]-[         Smallville.S09E10.720p.BluRay.x264-SiNNERS ] "Smallville.S09E10.720p.BluRay.x264-SiNNERS.part01.rar" (1/109) yEnc 50000000 Bytes  M0uSe <M0uSe@Leverage.com>      26 Dec 2014 20:18:15 GMT        <549dc286$0$57933$c3e8da3$c8b7d2e6@news.astraweb.com>           481548  3702    Xref: news-big.astraweb.com alt.binaries.teevee:714630771 alt.binaries.hdtv:4908878442


I am with astraweb.

**Comment by Murodese** [comment]
Interesting, that result shouldn't throw that exception. That print line was just before the NNTPDataError raise in the same block, right? ie.

    if token and token[:len(h)].lower() != h:
        print(line)
        raise NNTPDataError("OVER/XOVER response doesn't include "
                                        "names of additional headers")

The header parts are tab-separated as well, so I reconstructed where I assumed the tabs would go in order to test it - it's possible it's breaking somewhere non-obvious, so if you can get a dump including \t's, that'd work better.

`print(repr(line))`

**Comment by brookesy2** [comment]
Yup:

```python
def _parse_overview(lines, fmt, data_process_func=None):
    """Parse the response to a OVER or XOVER command according to the
    overview format `fmt`."""
    print(fmt)
    n_defaults = len(_DEFAULT_OVERVIEW_FMT)
    overview = []
    for line in lines:
        fields = {}
        article_number, *tokens = line.split('\t')
        article_number = int(article_number)
        for i, token in enumerate(tokens):
            if i >= len(fmt):
                # XXX should we raise an error? Some servers might not
                # support LIST OVERVIEW.FMT and still return additional
                # headers.
                continue
            field_name = fmt[i]
            is_metadata = field_name.startswith(':')
            if i >= n_defaults and not is_metadata:
                # Non-default header names are included in full in the response
                # (unless the field is totally empty)
                h = field_name + ": "
                if token and token[:len(h)].lower() != h:
                    print('{} {}'.format(i, token))
                    print(line)
                    raise NNTPDataError("OVER/XOVER response doesn't include "
                                        "names of additional headers")
                token = token[len(h):] if token else None
            fields[fmt[i]] = token
        overview.append((article_number, fields))
    return overview
```

Here is the extra logging:

4908878442      [REPOST]-[a.b.teevee]-[         Smallville.S09E10.720p.BluRay.x264-SiNNERS ] "Smallville.S09E10.720p.BluRay.x264-SiNNERS.part01.rar" (1/109) yEnc 50000000 Bytes        M0uSe <M0uSe@Leverage.com>      26 Dec 2014 20:18:15 GMT        <549dc286$0$57933$c3e8da3$c8b7d2e6@news.astraweb.com>            481548  3702    Xref: news-big.astraweb.com alt.binaries.teevee:714630771 alt.binaries.hdtv:4908878442
'4908878442\t[REPOST]-[a.b.teevee]-[ \tSmallville.S09E10.720p.BluRay.x264-SiNNERS ] "Smallville.S09E10.720p.BluRay.x264-SiNNERS.part01.rar" (1/109) yEnc 50000000 Bytes\tM0uSe <M0uSe@Leverage.com>\t26 Dec 2014 20:18:15 GMT\t<549dc286$0$57933$c3e8da3$c8b7d2e6@news.astraweb.com>\t\t481548\t3702\tXref: news-big.astraweb.com alt.binaries.teevee:714630771 alt.binaries.hdtv:4908878442'

**Comment by Murodese** [comment]
Yep, two problems there: 1) blank message-id (not allowed, message-id must exist and must be unique) and 2) an extraneous tab character in the message subject.

Let me investigate a bit.

**Comment by Murodese** [comment]
I've emailed Astraweb about no. 1, since that's their problem. It's possibly a DMCA'd post, but that should return a different error. They'll tell me what it is.

There's nothing I can do about no. 2. There's no way to determine whether a tab character is in a subject header erroneously, because nntplib splits based on tabs - the headers themselves would need to come through as quoted tsv, which they don't (to do so would require news server code changes, which are obviously not going to happen).

Either way, I'm going to kill any messages that have either of these problems, which will stop things from breaking.

**Comment by Murodese** [comment]
Ok, try that - completely untested, since I can't do it.

**Comment by brookesy2** [comment]
So far so good. I will let it run a while and let you know :) Where it used to crash instantly its processing. From reading the fix it makes sense, I definitely don't know enough about NNTP to have fixed it myself though!

**Comment by Murodese** [comment]
Hi James,

    Please try switching servers between US and EU, and try downloading the missing parts again, an see if it works. Thank you.

Thanks, Astraweb ~_~

**Comment by brookesy2** [comment]
Some very helpful advice.....

Things seem to be fine now. I will merge this change to my main install and
see how it goes.

**Comment by ukharley** [comment]
Now working fine for me as well.

**Comment by Murodese** [comment]
Cool, reopen if it breaks again.
